### ISSUE TITLE
cannot configure the DMA memory 1 address  in double buffer mode

### ISSUE THREAD

**Issue by FRASTM** [STMicroelectronics/STM32CubeL5#10]
The stm32L5  supports the DOUBLE BUFFER Mode for DMA transfer
The CUbe API to configure and set the address is for memory **target 0** only
LL_DMA_ConfigAddresses or LL_DMA_SetMemoryAddress are for the CM0AR 

However, there is no `LL_DMA_SetMemory1Address` to configure the CM1AR
 like in the _stm32f4xx_ll_dma.h_

**Comment by ASELSTM** [comment]
ST Internal Reference: 111843

**Comment by ASELSTM** [comment]
Hi @FRASTM,

The issue you reported has been fixed in the frame of version v1.5.0 of the STM32CubeL5 published on GitHub.

Thank you again for having reported.

With regards,
