### ISSUE TITLE
TFM not updated for STM32L562E-DK

### ISSUE THREAD

**Issue by LorenzoBinosi** [STMicroelectronics/STM32CubeL5#11]
**Project**
The project STM32CubeL5/Projects/STM32L562E-DK/Applications/TFM is not updated.
I tried to build it with 1 download slot instead of two and, once flashed, the Secure Boot doesn't find a valid image in the primary slot.

The flash_layout.h in the Linker directory doesn't suggest 1 as a valid define value for the macro MCUBOOT_IMAGE_NUMBER:
``` C
#ifndef __FLASH_LAYOUT_H__
#define __FLASH_LAYOUT_H__

/* This header file is included from linker scatter file as well, where only a
 * limited C constructs are allowed. Therefore it is not possible to include
 * here the platform_retarget.h to access flash related defines. To resolve this
 * some of the values are redefined here with different names, these are marked
 * with comment.
 */

/* Flash layout configuration : begin */
#define MCUBOOT_EXT_LOADER         /* Defined: Add external local loader application.
                                               To enter it, press user button at reset.
                                      Undefined: No external local loader application. */

#define TFM_EXTERNAL_FLASH_ENABLE  /* Defined: External OSPI flash used for S image secondary slot,
                                               and NS image primary and secondary slots.
                                      Undefined: External OSPI flash not used. */
/* Flash layout configuration : end */

#define MCUBOOT_IMAGE_NUMBER 2     /* 2: Two separated images for S and NS application binaries. */

...
```
Perhaps this project has been forgotten?

**Comment by ASELSTM** [comment]
ST Internal Reference: 123436

**Comment by ASELSTM** [comment]
Hi @LorenzoBinosi,

The  STM32L562E discovery kit provided example don't support the single image. This is documented in the user manual [UM2671](https://www.st.com/resource/en/user_manual/dm00678763-getting-started-with-stm32cubel5-tfm-application-stmicroelectronics.pdf)  in the **Table 4. Features configurability in TF-M based examples in the STM32CubeL5 package**.

This STM32L562E-DK/Applications/TFM  has been implemented for a secure image installed in the internal flash and a non-secure image installed in an external memory. Thus, for a single image example, you may refer to the [ SBSFU_Boot application](https://github.com/STMicroelectronics/STM32CubeL5/tree/master/Projects/NUCLEO-L552ZE-Q/Applications/SBSFU/SBSFU_Boot) developed for the Nucleo board.

A single image on the  STM32L562E-DK is of course possible but unfortunately we don't provide any example code.

Hope this would help you. Please allow me then to close this issue now. Thank you for your comprehension.

With regards,
