### ISSUE TITLE
Does STM32L552 have gcc support besides IDE(IAR, Keil,etc)

### ISSUE THREAD

**Issue by fangyuanseu** [STMicroelectronics/STM32CubeL5#4]
Hi experts,
    Does STM32L552 have gcc support besides IDE(IAR, Keil,etc), i think which will be easier for new RTOS developer from Linuxer, thanks in advance.

**Comment by fangyuanseu** [comment]
I'm so happy to know this task is added into TODO list, Thanks a lot!

**Comment by RKOUSTM** [comment]
Hi @fangyuanseu,

Allow me first to thank you for your contribution. Your report has been forwarded to our development team. We will get back to you as soon as we have more details.

With regards,

**Comment by PLFSTM** [comment]
Hi @fangyuanseu,

the only available support of gcc is coming with STM32CubeIDE and we do release for Linuxer too.

Regards
Patrice

**Comment by RKOUSTM** [comment]
Hi @PLFSTM,

Thank you @PLFSTM for your quick reply. 

Hi @fangyuanseu, 

Thank you for your contribution. I hope this answer helps. If you have no other question about this subject, I think this issue can be closed.

Thank you once again for your contribution.

With regards,

**Comment by fangyuanseu** [comment]
Hi @PLFSTM @RKOUSTM 
   Thanks for your quick feedback,  i will try STSTM32CubeIDE first and learn how to use this IDE.
   Thanks a again.
