### ISSUE TITLE
HAL_Delay() does not count timer ticks

### ISSUE THREAD

**Issue by Malek44** [STMicroelectronics/STM32CubeL5#6]
**Set-up**
 * Board: STM32L562E-DK
 * IDE: All.

**Description**
The implemented HAL_Delay(), [here](https://github.com/STMicroelectronics/STM32CubeL5/blob/master/Projects/STM32L562E-DK/Applications/FatFs/FatFs_uSD_TrustZone/Secure/Src/main.c#L346) and [here](https://github.com/STMicroelectronics/STM32CubeL5/blob/master/Projects/STM32L562E-DK/Applications/FatFs/FatFs_uSD_TrustZone/NonSecure/Core/Src/main.c#L267), does not appear to use the timer tick to count for the delay supposedly in milliseconds.

**Comment by ASELSTM** [comment]
Hi @Malek44,

The issue you pointed out is confirmed, an internal bug tracker has been logged and a fix will be implemented and made available in the frame of a future release. Thank you once again for your contribution.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 108588

**Comment by ASELSTM** [comment]
Hi @Malek44,

The issue you reported has been fixed in the frame of version v1.5.0 of the STM32CubeL5 published on GitHub.

Thank you again for having reported.

With regards,
